name: Test and Python Version

on:
  push:
    branches: [main]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run pylint
      run: pylint app.py

  python-version:
    runs-on: ubuntu-latest
    steps:
    - name: Display Python Version
      run: python --version

